name: FunBazeAPI
version: 1.0.2-RELEASE
author: DrKapdor
description: "Программный интерфейс взаимодействия с системами FunBaze"
website: "https://dev.funbaze.ru/"

depend:
  - ProtocolLib
  - NBTAPI
  - PluginMessagingAPI

main: me.drkapdor.funbazeapi.FunBazeApiPlugin

commands:
  addons: